image: golang:1.5.1
env:
  - GOPATH=/var/cache/drone
script:
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o dronetest .
  
publish:
  docker:
    docker_host: tcp://drone-worker.ipedrazas.k82.co.uk:2375
    image_name: dronetest
